import { ball, count, date, decimal, escape, percent } from "./charts.js";
import { methods, type BacktestResult, type Grid, type Method } from "./forecasts.js";
import type { Draw, Filters } from "./model.js";
export interface ForecastState {
 method:Method; quantity:number; seed:number; include:string; exclude:string; error:string; busy:boolean;
 generated:{grids:Grid[];method:Method;seed:number;through:string} | null;
 result:BacktestResult | null;
}
export const initialForecast = ():ForecastState=>({method:'random',quantity:5,seed:2026,include:'',exclude:'',error:'',busy:false,generated:null,result:null});
export function forecastsView(draws:Draw[],filters:Filters,state:ForecastState) {
 if(filters.regime!=='modern'||filters.kind!=='main')return `<section class="panel empty-state"><h2>Des grilles pour le LOTO moderne</h2><p>Le générateur propose cinq numéros et un numéro Chance. Sélectionnez le tirage principal du LOTO moderne pour l’utiliser.</p><button class="button primary" data-action="forecast-modern">Choisir le LOTO moderne</button></section>`;
 const descriptions:Record<Method,string>={random:"Chaque numéro disponible a le même poids. Le numéro Chance est uniforme entre 1 et 10.",frequency:"Le poids d’un numéro est son nombre d’apparitions dans la période + 1. Ce poids n’est pas une probabilité de sortie future.",delay:"Le poids d’un numéro est son retard dans la période + 1. Un numéro absent reçoit un retard borné à la taille de la période : il n’est pas « dû ».",balanced:"Les grilles contiennent deux ou trois numéros pairs. Ce critère de composition ne les rend pas plus susceptibles de gagner."};
 return `<div class="info-strip forecast-intro"><span><strong>Un laboratoire de grilles, pas une prédiction.</strong> Comparez vos critères au hasard, puis examinez ce qu’ils auraient donné sur des tirages passés. Les numéros Chance restent aléatoires dans les quatre méthodes.</span></div>
 <div class="forecast-layout"><section class="panel forecast-controls"><div class="panel-heading"><div><h2>Composer une série</h2><p>Source : ${count(draws.length)} tirages, jusqu’au ${date(draws.at(-1)!.date)}.</p></div><span class="chip">5 + CHANCE</span></div><form id="forecast-form"><label for="forecast-method">Méthode de composition</label><select id="forecast-method">${Object.entries(methods).map(([v,label])=>`<option value="${v}" ${state.method===v?'selected':''}>${label}</option>`).join('')}</select><p class="forecast-description">${descriptions[state.method]}</p><div class="forecast-fields"><div><label for="forecast-quantity">Nombre de grilles</label><input id="forecast-quantity" type="number" min="1" max="20" step="1" value="${state.quantity}" required></div><div><label for="forecast-seed">Graine reproductible</label><input id="forecast-seed" type="number" min="0" max="4294967295" step="1" value="${state.seed}" required></div></div><label for="forecast-include">Numéros imposés <span>facultatif · 5 maximum</span></label><input id="forecast-include" placeholder="Ex. 7, 23" value="${escape(state.include)}"><label for="forecast-exclude">Numéros exclus <span>facultatif</span></label><input id="forecast-exclude" placeholder="Ex. 1, 49" value="${escape(state.exclude)}"><div class="forecast-actions"><button class="button primary" type="submit">Générer les grilles</button><button class="button" type="button" data-action="forecast-seed">Nouvelle graine</button></div><p class="micro-copy">À paramètres et données identiques, une même graine recrée les mêmes grilles.</p></form></section>
 <section class="panel forecast-output"><div class="panel-heading"><div><h2>Vos grilles exploratoires</h2><p>${state.generated?`Dernière série : ${methods[state.generated.method]} · graine ${state.generated.seed}`:'Les propositions apparaîtront ici après génération.'}</p></div>${state.generated?'<span class="chip">EXPORT CSV DISPONIBLE</span>':''}</div>${state.generated?`<div class="generated-grids">${state.generated.grids.map((grid,i)=>`<div class="generated-grid"><span class="grid-index">${String(i+1).padStart(2,'0')}</span><div class="inline-balls">${grid.numbers.map(n=>ball(n,false,true)).join('')}<span class="grid-plus">+</span>${ball(grid.chance,true,true)}</div></div>`).join('')}</div><p class="table-caption">Générées avec les données disponibles jusqu’au ${date(state.generated.through)}. Les modifications du formulaire s’appliquent à la prochaine génération.</p>`:'<div class="empty-state compact"><h3>Des critères. Des grilles. Une comparaison.</h3><p>Commencez avec le hasard uniforme, puis explorez une autre méthode sur le même échantillon.</p></div>'}</section></div>
 ${state.error?`<p class="error-text forecast-error" role="alert">${escape(state.error)}</p>`:''}
 <section class="panel"><div class="panel-heading"><div><h2>Comparer la méthode au hasard</h2><p>Une grille par tirage et par méthode, répétée avec 20 graines.</p></div><button class="button primary" data-action="forecast-test" ${state.busy?'disabled':''}>${state.busy?'Simulation en cours…':'Lancer la comparaison'}</button></div><p class="forecast-explanation">La simulation réserve les 20 premiers tirages de votre sélection à l’apprentissage. Elle teste ensuite au maximum les 200 derniers, avec une fenêtre glissante de 50 tirages antérieurs au maximum. Les numéros imposés et exclus du générateur ne sont pas utilisés ici. Le nombre de grilles générées ne change pas le protocole.</p>${draws.length<21?'<p class="error-text">Il faut au moins 21 tirages sélectionnés pour lancer une comparaison.</p>':''}${state.result?resultView(state.result):'<div class="backtest-placeholder"><span>01 · Observer les tirages précédents</span><span>02 · Composer avant le résultat</span><span>03 · Mesurer face au hasard</span></div>'}</section>`;
}
function resultView(result:BacktestResult) {
 const a=result.strategy,b=result.baseline,delta=a.average-b.average;
 return `<div class="simulation-heading"><strong>${methods[result.method]}</strong><span>${count(result.draws)} tirages testés · ${date(result.first)} — ${date(result.last)} · graine ${result.seed}</span></div><div class="forecast-results"><article><span>Méthode choisie</span><strong>${decimal(a.average,3)}</strong><small>bons numéros par grille, en moyenne</small></article><article><span>Hasard uniforme</span><strong>${decimal(b.average,3)}</strong><small>bons numéros par grille, en moyenne</small></article><article><span>Écart observé</span><strong>${delta>0?'+':''}${decimal(delta,3)}</strong><small>un résultat passé, pas un avantage démontré</small></article></div><div class="table-scroll"><table><thead><tr><th>Indicateur</th><th>Méthode</th><th>Hasard</th></tr></thead><tbody><tr><td>Au moins 3 bons numéros</td><td>${percent(a.threePlus)}</td><td>${percent(b.threePlus)}</td></tr><tr><td>Numéro Chance correct</td><td>${percent(a.chanceRate)}</td><td>${percent(b.chanceRate)}</td></tr><tr><td>Moyenne : min.–max. des 20 répétitions</td><td>${decimal(a.low,3)} — ${decimal(a.high,3)}</td><td>${decimal(b.low,3)} — ${decimal(b.high,3)}</td></tr></tbody></table></div><p class="table-caption">Référence théorique : ${decimal(25/49,3)} bon numéro principal par grille et 10 % pour Chance. L’intervalle min.–max. montre la variation des simulations ; ce n’est pas un intervalle de confiance ni un test de supériorité. Aucun gain monétaire n’est estimé.</p><details class="simulation-audit"><summary>Voir les ${Math.min(8,result.trace.length)} derniers tests de la première répétition</summary><div class="table-scroll"><table><thead><tr><th>Tirage testé</th><th>Données utilisées jusqu’au</th><th>Grille de la méthode</th><th>Bons numéros</th><th>Hasard</th></tr></thead><tbody>${result.trace.slice(-8).map(row=>`<tr><td>${date(row.date)}</td><td>${date(row.trainedThrough)}</td><td>${row.grid.numbers.join(' · ')} + C${row.grid.chance}</td><td>${row.matches} / 5</td><td>${row.randomMatches} / 5</td></tr>`).join('')}</tbody></table></div></details>`;
}
