import { forecastsView, type ForecastState } from "./forecasts-view.js";
import { analyzeNumbers, analyzePairs, summarize, historyRows } from "./analytics.js";
import { ball, count, date, decimal, escape, frequencyChart, lineChart, percent } from "./charts.js";
import type { Dataset, Draw, Filters, NumberStat, View } from "./model.js";
export interface UIState { filters: Filters; view: View; selected: number; sort: string; pairNumber: number; page: number; query: string; queryNumbers: number[]; queryError: string; expanded: string; forecast: ForecastState }
export const icons: Record<string,string> = {
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  chart:'<path d="M4 20V10m8 10V4m8 16v-7"/>',
  pairs:'<circle cx="8" cy="9" r="5"/><circle cx="16" cy="15" r="5"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  arrow:'<path d="M5 12h14m-5-5 5 5-5 5"/>',
  download:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',
  refresh:'<path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 3M4 16l2 3a7 7 0 0 0 12-2"/>',
  info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',
  search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  chevron:'<path d="m9 5 7 7-7 7"/>'
};
export const icon=(name:string)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]??icons.grid}</svg>`;
const titles: Record<View,string>={overview:"Vue d’ensemble",numbers:"Analyse des numéros",pairs:"Explorer les paires",history:"Historique des tirages",forecasts:"Pronostics"};
const note = `<div class="disclaimer">${icon("info")}<p>Observer le passé, sans prédire l’avenir. Chaque tirage est indépendant ; les fréquences et retards ne changent pas les chances du prochain tirage.</p><button class="text-button" data-action="method">Comprendre les calculs ${icon("arrow")}</button></div>`;
export function shell(data:Dataset, state:UIState, draws:Draw[]) {
 const f=state.filters, first=draws[0]?.date, last=draws.at(-1)?.date;
 return `<aside class="sidebar"><a class="brand" href="#overview"><img src="./favicon.svg" width="35" height="35" alt=""><span>loto<span class="brand-slash">/</span>atelier<small>LE HASARD À LA LOUPE</small></span></a><div class="workspace-label">ESPACE PERSONNEL <span>01</span></div><nav aria-label="Navigation principale">${([["overview","grid"],["numbers","chart"],["pairs","pairs"],["history","clock"],["forecasts","check"]] as const).map(([v,i])=>`<a href="#${v}" class="nav-item ${state.view===v?"active":""}" ${state.view===v?'aria-current="page"':''}>${icon(i)}${titles[v]}${state.view===v?'<span class="nav-dot"></span>':''}</a>`).join("")}</nav><div class="sidebar-note"><div class="tiny-dot"></div><strong>Votre terrain d’exploration</strong><p>50 ans de tirages.<br>Une autre façon de les lire.</p><span>DEPUIS 1976 ${icon("arrow")}</span></div><div class="sidebar-bottom"><div class="source-label"><span class="status-dot"></span> Données officielles FDJ</div><p>${count(data.draws.length)} tirages disponibles<br>Dernier : ${date(data.draws.at(-1)?.date??null)}</p><button class="quiet-button" data-action="refresh">${icon("refresh")} Recharger les données</button><div class="profile"><span class="avatar">M</span><div>Mon atelier<small>Analyse locale · privée</small></div><span class="profile-dot"></span></div></div></aside>
 <div class="main-shell"><header class="topbar"><span>Mon espace <span class="breadcrumb-slash">/</span> <strong>${titles[state.view]}</strong></span><div class="topbar-right"><span class="private-badge">● Usage personnel</span><button class="icon-button" data-action="method" aria-label="Méthodologie">${icon("info")}</button></div></header><main id="content"><section class="page-heading"><div><p class="eyebrow">L’OBSERVATOIRE DU LOTO</p><h1>${state.view==="overview"?"Le hasard, sous tous les angles.":titles[state.view]}</h1><p class="subtitle">${state.view==="overview"?"Explorez les tirages. Repérez les variations. Affinez votre regard.":state.view==="numbers"?"Chaque numéro a une histoire. Explorez la sienne dans votre échantillon.":state.view==="pairs"?"Les numéros qui se sont rencontrés, et la fréquence de leurs rencontres.":state.view==="forecasts"?"Composez des grilles et confrontez vos critères au hasard.":"Retrouvez chaque tirage et composez votre propre lecture de l’historique."}</p></div><button class="button export-button" data-action="export">${icon("download")} Exporter en CSV</button></section>
 <section class="filters" aria-label="Filtres d’analyse"><div class="filter-field"><label for="regime">Régime de jeu</label><select id="regime"><option value="modern" ${f.regime==="modern"?"selected":""}>LOTO moderne · 5 + 1</option><option value="historic" ${f.regime==="historic"?"selected":""}>LOTO historique · 6 + 1</option></select></div><div class="filter-field"><label for="kind">Tirage</label><select id="kind" ${f.regime==="historic"?"disabled":""}><option value="main" ${f.kind==="main"?"selected":""}>Principal</option><option value="second" ${f.kind==="second"?"selected":""}>Second tirage</option></select></div><div class="filter-field window-filter"><label for="window">Période d’analyse</label><select id="window">${[["50","50 derniers tirages"],["100","100 derniers tirages"],["500","500 derniers tirages"],["all","Tout l’historique"],["custom","Dates personnalisées"]].map(([v,t])=>`<option value="${v}" ${f.window===v?"selected":""}>${t}</option>`).join("")}</select></div><button class="reset-button" data-action="reset" title="Rétablir les filtres par défaut">Réinitialiser</button>${f.window==="custom"?`<div class="custom-dates"><label>Du <input type="date" id="from" value="${f.from}"></label><label>Au <input type="date" id="to" value="${f.to}"></label>${f.from&&f.to&&f.from>f.to?'<span role="alert" class="error-text">La date de début doit précéder la date de fin.</span>':''}</div>`:''}</section>
 <div class="sample-caption"><span class="status-dot"></span><strong>${count(draws.length)} tirages sélectionnés</strong><span>${first&&last?`${date(first)} — ${date(last)}`:"Aucune date dans cet échantillon"}</span><span class="sample-tag">${f.regime==="modern"?"DEPUIS 2008":"1976 — 2008"}</span></div>
 ${!draws.length?`<section class="panel empty-state">${icon("search")}<h2>Aucun tirage dans cette période</h2><p>Élargissez les dates ou sélectionnez une autre période pour reprendre votre exploration.</p><button class="button primary" data-action="reset">Revenir aux 100 derniers tirages</button></section>`:state.view==="overview"?overview(draws,state):state.view==="numbers"?numbersView(draws,state):state.view==="pairs"?pairsView(draws,state):state.view==="forecasts"?forecastsView(draws,state.filters,state.forecast):historyView(draws,state)}
 ${note}<footer class="footer"><span>loto / atelier <span>·</span> Analyse descriptive</span><span>Source : archives publiques FDJ</span></footer></main></div>
 <dialog id="method-dialog"><div class="dialog-header"><span class="eyebrow">LES REPÈRES DE L’ATELIER</span><button class="icon-button" data-action="close-method" aria-label="Fermer">×</button></div><h2>Bien lire les chiffres.</h2><dl><dt>Fréquence observée</dt><dd>Nombre de tirages contenant le numéro, divisé par la taille de l’échantillon sélectionné.</dd><dt>Référence théorique</dt><dd>5/49 pour les numéros modernes, 6/49 pour l’historique, 1/10 pour Chance et 1/49 pour le complémentaire. Pour une paire : k × (k − 1) / (49 × 48).</dd><dt>Retard dans la période</dt><dd>Nombre de tirages sélectionnés depuis la dernière apparition. « ≥ N » signifie que le numéro est absent des N tirages de la période ; son retard complet est inconnu.</dd><dt>Sommes et répétitions</dt><dd>Les répétitions comparent deux tirages consécutifs de l’échantillon. Le graphique des sommes montre au maximum les 60 derniers tirages sélectionnés.</dd><dt>Données et confidentialité</dt><dd>Les calculs se font dans votre navigateur. Seuls les filtres sont mémorisés localement. Recharger lit le fichier du dépôt ; pour récupérer de nouveaux tirages, utilisez la commande npm run update dans le projet.</dd></dl><p class="method-warning">Un écart historique n’indique pas une meilleure chance de gagner. Aucune prédiction n’est produite.</p><button class="button primary" data-action="close-method">J’ai compris</button></dialog>`;
}
function sortedStats(draws:Draw[]) { return analyzeNumbers(draws,49,draws[0]?.numbers.length??5); }
function numberDetail(draws:Draw[], selected:number, rows:NumberStat[]) {
 const row=rows[selected-1];
 const appearances=draws.slice(-40).map(d=>d.numbers.includes(selected));
 return `<section class="panel number-detail"><div class="panel-heading"><span class="eyebrow">ZOOM SUR UN NUMÉRO</span>${icon("chart")}</div><div class="number-hero">${ball(selected)}<div><h2>Numéro ${selected}</h2><span>${row.count} apparition${row.count>1?'s':''} sur ${draws.length} tirages</span></div></div><div class="detail-stats"><div><span>Fréquence</span><strong>${percent(row.rate)}</strong></div><div><span>Retard</span><strong>${row.censored?'≥ ':''}${row.delay}<small> tirages</small></strong></div></div><div class="deviation"><span>Écart à la référence</span><strong class="${row.delta>=0?'positive':'muted'}">${row.delta>0?'+':''}${decimal(row.delta*100)} pts</strong></div><p class="timeline-label">${appearances.length} DERNIERS TIRAGES <span>● Présent</span></p><div class="appearance-timeline" role="img" aria-label="Présence du numéro ${selected} dans les ${appearances.length} derniers tirages">${appearances.map((yes,i)=>`<span class="${yes?'hit':''}" title="${date(draws.slice(-40)[i].date)} : ${yes?'présent':'absent'}"></span>`).join("")}</div><div class="last-seen">Dernière apparition <strong>${date(row.lastDate)}</strong></div><p class="micro-copy">Cliquez sur un numéro du graphique pour l’explorer.</p></section>`;
}
function overview(draws:Draw[],state:UIState) {
 const rows=sortedStats(draws), top=[...rows].sort((a,b)=>b.count-a.count||a.number-b.number)[0], late=[...rows].sort((a,b)=>b.delay-a.delay||a.number-b.number)[0], stats=summarize(draws), latest=draws.at(-1)!;
 return `<section class="overview-intro"><div class="insight-intro"><span class="eyebrow">VOTRE ÉCHANTILLON, EN UN COUP D’ŒIL</span><h2>Les chiffres racontent<br>une partie de l’histoire.</h2><p>Un point de départ pour explorer vos ${count(draws.length)} tirages, à votre rythme.</p><a class="text-button" href="#numbers">Explorer les 49 numéros ${icon("arrow")}</a></div><div class="latest-card"><div class="latest-heading"><span><span class="live-dot"></span> DERNIER TIRAGE DE LA SÉLECTION</span><span>${date(latest.date)}</span></div><div class="latest-balls">${[...latest.numbers].sort((a,b)=>a-b).map(n=>ball(n)).join("")}${state.filters.kind==="main"?`<span class="ball-divider"></span>${ball(latest.bonus,true)}`:''}</div><div class="latest-footer"><span>${state.filters.kind==="second"?"Second tirage":state.filters.regime==="modern"?"5 numéros + numéro Chance":"6 numéros + complémentaire"}</span><a href="#history" aria-label="Voir l’historique">${icon("arrow")}</a></div></div></section>
 <section class="metrics"><article class="metric"><span class="metric-label">Tirages analysés ${icon("grid")}</span><strong>${count(draws.length)}</strong><small>${date(draws[0].date)} → ${date(latest.date)}</small></article><article class="metric"><span class="metric-label">Le plus fréquent ${icon("chart")}</span><div class="metric-number">${ball(top.number,true,true)}<strong>${top.count}<small> sorties</small></strong></div><small>${percent(top.rate)} des tirages sélectionnés</small></article><article class="metric"><span class="metric-label">Le plus grand retard ${icon("clock")}</span><div class="metric-number">${ball(late.number,false,true)}<strong>${late.censored?'≥ ':''}${late.delay}<small> tirages</small></strong></div><small>Retard mesuré dans cette période</small></article><article class="metric"><span class="metric-label">Somme moyenne ${icon("pairs")}</span><strong>${decimal(stats.averageSum)}</strong><small>Référence théorique : ${draws[0].numbers.length*25}</small></article></section>
 <div class="analysis-grid"><section class="panel frequency-panel"><div class="panel-heading"><div><h2>Fréquence des numéros</h2><p>Combien de fois chaque numéro est-il apparu ?</p></div><span class="chip">1 — 49</span></div>${frequencyChart(rows,draws.length,state.selected)}<div class="chart-legend"><span><i class="legend-square coral"></i> Nombre d’apparitions</span><span><i class="legend-line"></i> Référence : ${decimal(draws.length*rows[0].expectedRate)} sorties</span></div></section>${numberDetail(draws,state.selected,rows)}</div>
 <div class="two-columns"><section class="panel"><div class="panel-heading"><div><h2>La forme des tirages</h2><p>Répartition des numéros pairs et impairs</p></div><span class="chip">PARITÉ</span></div><div class="parity-summary"><strong>${percent(stats.evenRate)}<small>pairs</small></strong><div class="parity-track"><span style="width:${stats.evenRate*100}%"></span></div><strong>${percent(1-stats.evenRate)}<small>impairs</small></strong></div><div class="parity-distribution">${stats.parity.map((v,i)=>`<div><span>${i} P / ${draws[0].numbers.length-i} I</span><strong>${v}</strong><div style="--fill:${v/Math.max(1,...stats.parity)*100}%"></div></div>`).join("")}</div></section><section class="panel"><div class="panel-heading"><div><h2>Au fil des sommes</h2><p>Somme des numéros · ${Math.min(60,draws.length)} derniers tirages</p></div><span class="chip">TENDANCE</span></div>${lineChart(stats.sums.slice(-60),draws[0].numbers.length*25)}<div class="chart-legend between"><span>${date(draws.slice(-60)[0].date)}</span><span>${date(latest.date)}</span></div></section></div>
 <section class="panel recent"><div class="panel-heading"><div><h2>Les derniers tirages</h2><p>Un regard sur les cinq tirages les plus récents de la sélection</p></div><a class="text-button" href="#history">Tout l’historique ${icon("arrow")}</a></div>${drawTable(draws.slice(-5).reverse(),state)}</section>`;
}
function numbersView(draws:Draw[],state:UIState) {
 const rows=sortedStats(draws), max=Math.max(1,...rows.map(r=>r.count));
 const sorted=[...rows].sort(state.sort==="delay"?(a,b)=>b.delay-a.delay||a.number-b.number:state.sort==="number"?(a,b)=>a.number-b.number:(a,b)=>b.count-a.count||a.number-b.number);
 const bonus=state.filters.kind==="main"?analyzeNumbers(draws,state.filters.regime==="modern"?10:49,1,true):[];
 return `<div class="analysis-grid"><section class="panel"><div class="panel-heading"><div><h2>La carte des 49 numéros</h2><p>Plus la teinte est soutenue, plus le numéro est sorti.</p></div><span class="chip">FRÉQUENCES</span></div><div class="number-map">${rows.map(r=>`<button data-number="${r.number}" class="number-tile ${r.number===state.selected?'selected':''}" style="--heat:${r.count/max*.75}" aria-pressed="${r.number===state.selected}"><strong>${String(r.number).padStart(2,'0')}</strong><span>${r.count} sorties</span></button>`).join("")}</div></section>${numberDetail(draws,state.selected,rows)}</div>
 <section class="panel"><div class="panel-heading"><div><h2>Tous les indicateurs</h2><p>La référence est de ${percent(rows[0].expectedRate)} par tirage.</p></div><label class="inline-select">Trier par <select id="number-sort"><option value="count" ${state.sort==='count'?'selected':''}>Fréquence</option><option value="delay" ${state.sort==='delay'?'selected':''}>Retard</option><option value="number" ${state.sort==='number'?'selected':''}>Numéro</option></select></label></div><div class="table-scroll"><table><thead><tr><th>Numéro</th><th>Sorties</th><th>Fréquence</th><th>Écart théorique</th><th>Retard</th><th>Dernière apparition</th></tr></thead><tbody>${sorted.map(r=>`<tr class="${r.number===state.selected?'highlight-row':''}"><td><button class="ball-button" data-number="${r.number}" aria-label="Explorer le numéro ${r.number}">${ball(r.number,false,true)}</button></td><td><strong>${r.count}</strong></td><td>${percent(r.rate)}</td><td class="${r.delta>0?'positive':''}">${r.delta>0?'+':''}${decimal(r.delta*100)} pts</td><td>${r.censored?'≥ ':''}${r.delay} tirages</td><td>${date(r.lastDate)}</td></tr>`).join("")}</tbody></table></div></section>
 ${bonus.length?`<section class="panel bonus-panel"><div class="panel-heading"><div><h2>${state.filters.regime==='modern'?'Le numéro Chance':'La boule complémentaire'}</h2><p>Une distribution séparée des numéros principaux.</p></div></div><div class="bonus-grid">${bonus.map(r=>`<div>${ball(r.number,true,true)}<strong>${r.count}</strong><span>${percent(r.rate)}</span></div>`).join("")}</div></section>`:''}`;
}
function pairsView(draws:Draw[],state:UIState) {
 const all=analyzePairs(draws), filtered=all.filter(p=>!state.pairNumber||p.a===state.pairNumber||p.b===state.pairNumber), rows=filtered.slice(0,40), k=draws[0].numbers.length;
 return `<section class="panel"><div class="panel-heading"><div><h2>Les rencontres les plus fréquentes</h2><p>Chaque paire est comptée une seule fois par tirage, quel que soit l’ordre.</p></div><label class="inline-select">Avec le numéro <select id="pair-number"><option value="0">Tous les numéros</option>${Array.from({length:49},(_,i)=>`<option value="${i+1}" ${state.pairNumber===i+1?'selected':''}>${i+1}</option>`).join("")}</select></label></div><div class="pair-podium">${rows.slice(0,3).map((p,i)=>`<article><span class="eyebrow">${String(i+1).padStart(2,'0')} / DANS LA SÉLECTION</span><div>${ball(p.a)}${ball(p.b)}</div><strong>${p.count} <small>rencontres</small></strong><span>${percent(p.rate)} des tirages</span></article>`).join("")}</div><div class="info-strip">${icon("info")}<span>Référence théorique d’une paire : <strong>${percent(k*(k-1)/(49*48))}</strong> par tirage. Le classement est descriptif, sans pouvoir prédictif.</span></div><div class="table-scroll"><table><thead><tr><th>Rang</th><th>Paire</th><th>Rencontres</th><th>Fréquence</th><th>Répartition relative</th></tr></thead><tbody>${rows.map((p,i)=>`<tr><td class="muted">${String(i+1).padStart(2,'0')}</td><td><div class="inline-balls">${ball(p.a,false,true)}${ball(p.b,false,true)}</div></td><td><strong>${p.count}</strong></td><td>${percent(p.rate)}</td><td><div class="mini-track"><span style="width:${p.count/Math.max(1,rows[0].count)*100}%"></span></div></td></tr>`).join("")}</tbody></table></div><p class="table-caption">${rows.length} paires affichées sur ${filtered.length}. L’export contient toutes les paires correspondant au filtre.</p></section>`;
}
export function drawTable(draws:Draw[],state:UIState) {
 return `<div class="table-scroll"><table class="draw-table"><thead><tr><th>Date du tirage</th><th>Numéros ${state.filters.kind==='second'?'du second tirage':''}</th>${state.filters.kind==='main'?`<th>${state.filters.regime==='modern'?'Chance':'Compl.'}</th>`:''}<th>Somme</th><th>Pairs / impairs</th><th><span class="sr-only">Détails</span></th></tr></thead><tbody>${draws.map(d=>{
 const key=`${d.date}|${d.id}`,expanded=key===state.expanded;
 return `<tr><td><strong>${date(d.date)}</strong><small class="draw-id">N° ${escape(d.id)}</small></td><td><div class="inline-balls">${[...d.numbers].sort((a,b)=>a-b).map(n=>ball(n,false,true)).join("")}</div></td>${state.filters.kind==='main'?`<td>${ball(d.bonus,true,true)}</td>`:''}<td>${d.numbers.reduce((a,b)=>a+b,0)}</td><td><span class="parity-badge">${d.numbers.filter(n=>n%2===0).length} P <span>/</span> ${d.numbers.filter(n=>n%2!==0).length} I</span></td><td><button class="icon-button" data-draw="${escape(key)}" aria-label="Détails du tirage du ${date(d.date)}" aria-expanded="${expanded}">${icon('chevron')}</button></td></tr>${expanded?`<tr class="expanded-row"><td colspan="6"><strong>Ordre de sortie FDJ</strong> ${d.numbers.join(' · ')}<span>Amplitude : ${Math.max(...d.numbers)-Math.min(...d.numbers)}</span>${d.second&&state.filters.kind==='main'?`<span>Second tirage : ${d.second.join(' · ')}</span>`:''}</td></tr>`:''}`;
 }).join("")}</tbody></table></div>`;
}
function historyView(draws:Draw[],state:UIState) {
 const matches=state.queryError?[]:historyRows(draws,state.queryNumbers), size=20, pages=Math.max(1,Math.ceil(matches.length/size)), page=Math.min(state.page,pages-1);
 return `<section class="panel"><div class="panel-heading history-heading"><div><h2>Votre historique, à la carte</h2><p>${count(matches.length)} résultat${matches.length>1?'s':''} dans la période sélectionnée</p></div><form id="history-search" class="search-form"><label class="sr-only" for="history-query">Numéros à rechercher</label>${icon('search')}<input id="history-query" placeholder="Numéros, ex. 7, 23" value="${escape(state.query)}"><button class="button" type="submit">Rechercher</button></form></div><p class="search-hint">La recherche conserve les tirages contenant <strong>tous</strong> les numéros saisis. Les statistiques des autres vues restent inchangées.</p>${state.queryError?`<p class="error-text" role="alert">${escape(state.queryError)}</p>`:''}${matches.length?drawTable(matches.slice(page*size,(page+1)*size),state):'<div class="empty-state compact"><h3>Aucun tirage correspondant</h3><p>Essayez moins de numéros ou élargissez la période.</p></div>'}<div class="pagination"><span>${matches.length?page*size+1:0}–${Math.min((page+1)*size,matches.length)} sur ${count(matches.length)} tirages</span><div><button class="button" data-page="${page-1}" ${page===0?'disabled':''}>← Précédent</button><span>${page+1} / ${pages}</span><button class="button" data-page="${page+1}" ${page>=pages-1?'disabled':''}>Suivant →</button></div></div></section>`;
}
